# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - destroy
 
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - linux
    - macos
    - shared
    - windows


  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
 
unit-test-job:   # This job runs in the test stage.
  image: openjdk:11
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - bundle install
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    when: always
    paths:
     - rspec.xml
    reports:
      junit: rspec.xml
 
check-files-job:  # This job runs in the test stage.
   stage: test
   image: alpine:latest
   script:
      - mkdir checkdir
      - find -name *.c > checkdir/testresult.txt 2>/dev/null
   artifacts:
        paths:
          - ./checkdir
 
deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
 
deploy_to_cloud:  # This job runs in the deploy stage.
    stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
    image: google/cloud-sdk:alpine
    script:
        - echo "Deploying to gcloud..."
